-- Creación de vista de clientes tipo marino con sus contactos y barcos asociados.

CREATE OR REPLACE FORCE EDITIONABLE VIEW "LIBRA"."EN_CLI_MARINO" ("EMPRESA", "CLIENTE", "NOMBRE", "CONTACTO","TELEFONO","EMAIL","BARCO","IMO","PUERTO") AS 
SELECT CLI.CODIGO_EMPRESA, CLI.CODIGO_RAPIDO, CLI.NOMBRE, AG.PERSONA_CONTACTO, NVL(AG.MOVIL, AG.TELEFONO) TELEFONO, AG.INTERNET EMAIL,
BAR.NOMBRE, BAR.IMO, BAR.PUERTO_BASE
FROM CLIENTES CLI
INNER JOIN AGENDA_CLIENTES AG
ON AG.CODIGO_EMPRESA = CLI.CODIGO_EMPRESA
AND AG.CODIGO_RAPIDO = CLI.CODIGO_RAPIDO
LEFT JOIN EN_BARCOS BAR
ON BAR.EMPRESA = CLI.CODIGO_EMPRESA
AND BAR.CLIENTE_BLOQUEO = CLI.CODIGO_RAPIDO
WHERE CLI.TIPO_CLIENTE = 'M';


-- Creación de vista de artículos de tipo marino con su precio de lista 2 (consumo).

CREATE OR REPLACE FORCE EDITIONABLE VIEW "LIBRA"."EN_ART_MARINO" ("EMPRESA", "ARTICULO", "DESCRIPCION", "PRECIO") AS 
SELECT AR.CODIGO_EMPRESA, AR.CODIGO_ARTICULO, AR.DESCRIP_COMERCIAL, PL.PRECIO_CONSUMO
FROM ARTICULOS AR
INNER JOIN PRECIOS_LISTAS PL
ON PL.CODIGO_EMPRESA = AR.CODIGO_EMPRESA AND PL.CODIGO_ARTICULO = AR.CODIGO_ARTICULO
AND PL.NUMERO_LISTA = '2' AND PL.ORGANIZACION_COMERCIAL IN ('1','P1')
AND PL.FECHA_VALIDEZ = (SELECT MAX(PL2.FECHA_VALIDEZ) FROM PRECIOS_LISTAS PL2
WHERE PL2.CODIGO_EMPRESA = PL.CODIGO_EMPRESA AND PL2.ORGANIZACION_COMERCIAL = PL.ORGANIZACION_COMERCIAL
AND PL2.NUMERO_LISTA = PL.NUMERO_LISTA AND PL2.CODIGO_ARTICULO = PL.CODIGO_ARTICULO)
ORDER BY AR.CODIGO_ARTICULO, AR.CODIGO_EMPRESA;